name: Deploy to staging Server

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Add PHPUnit Tests
      - name: PHPUnit Tests Chalayein
        run: phpunit tests/

      - name: Build Docker Image
        run: |
          docker build -t daniyalmirza/blogpost:staging .
          docker push daniyalmirza/blogpost:staging


      - name: Set up SSH and Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Log in to Docker registry
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      
            # Pull the Docker image
            docker pull daniyalmirza/blogpost:staging
      
            # Run the Docker container
            docker run -d -p 8080:80 daniyalmirza/blogpost:staging
